### ISSUE TITLE
[Init] 프로젝트 생성 및 개발환경 설정

### ISSUE THREAD

**Issue by juwon-code** [juwon-code/common-blog-project#1]
### Description
프로젝트를 생성하고 개발환경을 설정합니다.

### ToDo

- [x] Spring Boot Project 생성
- [x] Dependency 주입 및 설정
- [x] 데이터베이스 연동
- [x] Git Action 워크플로 작성
- [x] DockerHub 연동

**Comment by juwon-code** [comment]
**Intellij**의 `Spring Initializr`를 사용하여 프로젝트를 생성했습니다.

**Version**은 `3.2.0` 이고, **JDK**는 `17`을 사용하며, **빌드 도구**는 `Gradle-Kotlin`입니다.

현재 설치한 Dependency 목록은 아래와 같으며,  필요한 경우 계속 추가할 예정입니다.

- `Spring Boot DevTools` : **Live Reload**, **Automatic Restart** 기능을 제공하여 개발 속도를 높일 수 있습니다.
- `Lombok` : 각종 생성자와 **getter()**, **setter()**, **toString()** 등을 어노테이션으로 제공합니다.
- `Spring Web` : **Spring MVC**, **REST** 서버 구현을 위해 필요한 라이브러리를 통합 제공합니다.
- `Spring Data JPA` : Java의 **ORM**을 위한 표준 인터페이스를 제공합니다.
- `MariaDB Java Client` : MariaDB, MySQL에 접속하기 위해 **JDBC**를 제공하는 드라이버입니다.

**Comment by juwon-code** [comment]
Dependency 설정에 사용하는 .properties는 3개의 파일로 나누어서 관리합니다.

- `application` : 프로필로 나눌 필요 없는 공통적인 설정을 담당합니다.
- `application-local` : 개발환경에서 사용할 설정들을 담고 있습니다.
- `application-prod` : 배포환경에서 사용할 설정들을 담고 있습니다.

`application-local`의 연결 정보는 공개해도 무방하다고 판단되어 커밋합니다. 설령 외부 IP 주소를 안다고 해도 외부에서 접근할 수 없도록 설정하였습니다.

`application-prod`의 연결 정보는 Github Repository의 secret으로 관리되며, Github Action 워크플로의 빌드 과정에서 삽입됩니다.

---

프로젝트의 로그 관리에는 `Spring Boot DevTools`에 포함되어 있는 `SLF4J`와 `Logback`을 사용합니다. 개발 환경과 배포 환경을 고려하여 다음과 같이 설정했습니다.

- 개발 환경에서 로그는 콘솔에 출력되며 INFO 레벨까지 관리합니다.
- 배포 환경에서 로그는 파일로 저장되며 ERROR 레벨까지 관리합니다.
